[package]
name = "polish-cow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
gemini-engine = "0.12.0"
rodio = "0.17.3"
stl_io = "0.7.0"
