name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: rust:1.76

    steps:
    - uses: actions/checkout@v3

    - name: Install necessary sound libraries
      run: apt-get update && apt-get -y install libasound2-dev

    - name: Build production release for various platforms
      run: |
        echo "Adding supported targets to the rustup toolchain"
        # x86 64bit architectures
        rustup target add x86_64-unknown-linux-gnu
        rustup target add x86_64-pc-windows-gnu
        rustup target add x86_64-apple-darwin
        # x86 32bit architectures
        rustup target add i686-unknown-linux-gnu
        rustup target add i686-pc-windows-gnu
        
        # ARM 64bit architectures
        rustup target add aarch64-unknown-linux-gnu
        rustup target add aarch64-apple-darwin

        # RISC-V 64bit architectures
        rustup target add riscv64gc-unknown-linux-gnu

        # Build the release
        cargo build --release --target x86_64-unknown-linux-gnu
        cargo build --release --target x86_64-pc-windows-gnu
        cargo build --release --target x86_64-apple-darwin
        cargo build --release --target i686-unknown-linux-gnu
        cargo build --release --target i686-pc-windows-gnu
        cargo build --release --target aarch64-unknown-linux-gnu
        cargo build --release --target aarch64-apple-darwin
        cargo build --release --target riscv64gc-unknown-linux-gnu

    - name: Run tests in release mode
      run: cargo test -r
    
    # upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          target/x86_64-unknown-linux-gnu/release/polish-cow
          target/x86_64-pc-windows-gnu/release/polish-cow.exe
          target/x86_64-apple-darwin/release/polish-cow
          target/i686-unknown-linux-gnu/release/polish-cow
          target/i686-pc-windows-gnu/release/polish-cow.exe
          target/aarch64-unknown-linux-gnu/release/polish-cow
          target/aarch64-apple-darwin/release/polish-cow
          target/aarch64-pc-windows-gnu/release/polish-cow.exe
          target/riscv64gc-unknown-linux-gnu/release/polish-cow
